name: Build Project

on:
  push:
    branches-ignore:
      - 'dependabot/*'
    tags-ignore:
      - r[0-9]*
  workflow_dispatch:

env:
  LATEST_DRIVER: 4.9.1

jobs:
  Build:
    uses: evanchooly/workflows/.github/workflows/build.yml@master
    with:
      java: 20
      saveBuild: true
      maven-flags: "-Dmongodb=6"

  Test:
    needs:
      - Build
    strategy:
      matrix:
        java: [ 20, 11 ]
        mongo: [ 6 ]
        driver: [ ${{ env.LATEST_DRIVER }}, 4.8.1, 4.7.2, 4.6.1 ]
        include:
          - java: 11
            mongo: 5
            driver: ${{ env.LATEST_DRIVER }}
          - java: 11
            mongo: 4.4
            driver: ${{ env.LATEST_DRIVER }}
          - java: 11
            mongo: 4.2
            driver: ${{ env.LATEST_DRIVER }}
          - java: 11
            mongo: 4.0
            driver: ${{ env.LATEST_DRIVER }}

    uses: evanchooly/workflows/.github/workflows/build.yml@master
    secrets:
      GH_TOKEN: ${{ secrets.TESTING_GH_OAUTH }}
    with:
      java: ${{ matrix.java }}
      reuseBuild: true
      archive-name: "${{matrix.mongo}}-${{matrix.driver}}-${{matrix.java}}-${{github.run_id}}"
      maven-flags: "-Dmongodb=${{ matrix.mongo }} -Ddriver.version=${{ matrix.driver }}"

  Snapshots:
    if: github.ref_type == 'branch'
    needs:
      - Test
    uses: evanchooly/workflows/.github/workflows/release.yml@master
    secrets:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GH_TOKEN: ${{ secrets.GH_OAUTH }}

  Docs:
    name: Update Documentation
    runs-on: ubuntu-latest
    needs:
      - Snapshots
    steps:
      - name: Invoke antora build
        uses: benc-uk/workflow-dispatch@v121
        with:
          workflow: Docs
          repo: MorphiaOrg/morphia-docs
          token: ${{ secrets.PUSH_TOKEN }}
          ref: refs/heads/master

  Critter:
    name: Build Critter snapshot
    needs:
      - Snapshots
    runs-on: ubuntu-latest
    steps:
      - name: Invoke critter build
        uses: benc-uk/workflow-dispatch@v121
        with:
          workflow: "Build Project"
          repo: MorphiaOrg/critter
          token: ${{ secrets.PUSH_TOKEN }}
          ref: refs/heads/master
