name: Build Project

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  CodeAudits:
    uses: evanchooly/workflows/.github/workflows/code-audits.yml@master
  Build:
    uses: evanchooly/workflows/.github/workflows/build.yml@master
    with:
      saveBuild: true

  Test:
    needs:
      - CodeAudits
      - Build
    strategy:
      matrix:
        java: [ 11 ]
        mongo: [ 6.0.4, 5.0.15, 4.4.19, 4.2.24, 4.0.28 ]
        driver: [ 4.6.1, 4.7.2 ]
        include:
          - java: 19
            mongo: 6.0.4
            driver: 4.7.2
          - java: 20
            mongo: 6.0.4
            driver: 4.7.2

    uses: evanchooly/workflows/.github/workflows/build.yml@master
    with:
      java: ${{ matrix.java }}
      reuseBuild: true
      archive-name: "${{matrix.mongo}}-${{matrix.driver}}-${{matrix.java}}-${{github.run_id}}"
      maven-flags: "-e -Dmongodb=${{ matrix.mongo }} -Ddriver.version=${{ matrix.driver }}"

  Release:
    if: github.ref_type == 'branch' || github.ref_type == 'tag'
    needs:
      - Test
    uses: evanchooly/workflows/.github/workflows/jreleaser.yml@master
    secrets:
      GH_PUSH_TOKEN       : ${{ secrets.GH_PUSH_TOKEN }}
      GPG_PASSPHRASE      : ${{ secrets.GPG_PASSPHRASE }}
      GPG_PUBLIC_KEY      : ${{ secrets.GPG_PUBLIC_KEY }}
      GPG_PRIVATE_KEY     : ${{ secrets.GPG_PRIVATE_KEY }}
      SONATYPE_USERNAME   : ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD   : ${{ secrets.SONATYPE_PASSWORD }}

  Docs:
    name: Update Documentation
    runs-on: ubuntu-latest
    needs:
      - Release
    steps:
      - name: Invoke antora build
        uses: benc-uk/workflow-dispatch@v121
        with:
          workflow: Docs
          repo: MorphiaOrg/morphia-docs
          token: ${{ secrets.GH_PUSH_TOKEN }}
          ref: refs/heads/master