name: Build Project

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    tags:
      - r[0-9]*
  workflow_dispatch:

jobs:
  CodeAudits:
    uses: evanchooly/workflows/.github/workflows/code-audits.yml@master
    with:
      java: 17
  Build:
    uses: evanchooly/workflows/.github/workflows/build.yml@master
    with:
      java: 20
      saveBuild: true
  Matrix:
    runs-on: ubuntu-latest
    steps:
      - id: mongo-versions
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - app setup
          echo '::set-output name=version_matrix::$( ~/.jbang/bin/jbang .github/BuildMatrix.java \ )'
    outputs:
      version_matrix: ${{ steps.mongo-versions.outputs.version_matrix }}

  Test:
    needs:
      - CodeAudits
      - Build
      - Matrix
    strategy:
      matrix:
        java: [ 20, 17 ]
        mongo: ${{ fromJson(needs.matrix.outputs.version_matrix) }}
        driver: [ 4.10.2 ]
        include:
          - java: 17
            mongo: 7
            driver: 4.9.1
          - java: 17
            mongo: 7
            driver: 4.8.2
          - java: 17
            mongo: 7
            driver: 4.7.2
          - java: 17
            mongo: 7
            driver: 4.6.1
          - java: 17
            mongo: 7
            driver: 4.5.1
          - java: 17
            mongo: 7
            driver: 4.4.2
            optional: true
          - java: 17
            mongo: 7
            driver: 4.3.4
            optional: true
          - java: 17
            mongo: 7
            driver: 4.2.3
            optional: true
          - java: 17
            mongo: 7
            driver: 4.1.2
            optional: true
          - java: 17
            mongo: 7
            driver: 4.0.6
            optional: true

    uses: evanchooly/workflows/.github/workflows/build.yml@master
    with:
      java: ${{ matrix.java }}
      reuseBuild: true
      archive-name: "${{matrix.mongo}}-${{matrix.driver}}-${{matrix.java}}-${{github.run_id}}"
      maven-flags: "-e -Dmongodb=${{ matrix.mongo }} -Ddriver.version=${{ matrix.driver }}"

  Release:
    if: github.ref_type == 'branch' || github.ref_type == 'tag'
    needs:
      - Test
    uses: evanchooly/workflows/.github/workflows/release.yml@master
    with:
      java: 20
    secrets:
      GH_PUSH_TOKEN       : ${{ secrets.GH_PUSH_TOKEN }}
      GPG_PASSPHRASE      : ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY     : ${{ secrets.GPG_PRIVATE_KEY }}
      SONATYPE_USERNAME   : ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD   : ${{ secrets.SONATYPE_PASSWORD }}

  Docs:
    name: Update Documentation
    runs-on: ubuntu-latest
    needs:
      - Release
    steps:
      - name: Invoke antora build
        uses: benc-uk/workflow-dispatch@v121
        with:
          workflow: Docs
          repo: MorphiaOrg/morphia-docs
          token: ${{ secrets.GH_PUSH_TOKEN }}
          ref: refs/heads/master