name: Build Project

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:

jobs:
  Build:
    uses: evanchooly/workflows/.github/workflows/build.yml@master
    with:
      saveBuild: true
      maven-flags: "-Dmongodb=6.0.2 -Dcode-audits"

  Test:
    needs:
      - Build
    strategy:
      matrix:
        java: [ 11, 19 ]
        mongo: [ 6.0.2, 5.0.13, 4.4.17, 4.2.23 ]
    uses: evanchooly/workflows/.github/workflows/build.yml@master
    secrets:
      GH_TOKEN: ${{ secrets.TESTING_GH_OAUTH }}
    with:
      java: ${{ matrix.java }}
      reuseBuild: true
      archive-name: "${{matrix.mongo}}-${{matrix.java}}"
      maven-flags: "-DMONGODB=${{ matrix.mongo }}"

  Snapshots:
    if: github.ref_type == 'branch'
    needs:
      - Test
    uses: evanchooly/workflows/.github/workflows/release.yml@master
    secrets:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GH_TOKEN: ${{ secrets.GH_OAUTH }}

  Docs:
    name: Update Documentation
    runs-on: ubuntu-latest
    needs:
      - Snapshots
    steps:
      - name: Invoke antora build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Docs
          repo: MorphiaOrg/morphia-docs
          token: ${{ secrets.PUSH_TOKEN }}
          ref: refs/heads/master
