name: Pull Requests

on:
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  Build:
    uses: evanchooly/workflows/.github/workflows/pull-request.yml@master
    with:
      maven-flags: "-DMONGODB=6.0.1"
