name: Pull Requests

on:
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  CodeAudits:
    uses: evanchooly/workflows/.github/workflows/code-audits.yml@master
    with:
      java: 17
  Build:
    needs:
      - CodeAudits
    uses: evanchooly/workflows/.github/workflows/pull-request.yml@master
    with:
      java: 17
