name: Rewrite Tests

on:
  push:
    branches:
      - 'master'
      - '2.4.x'
  workflow_dispatch:

jobs:
  Rewrite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 2.4.x
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          server-id: central
          cache: maven
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: >
            [
              {
                "id": "snapshot-repository",
                "url": "https://oss.sonatype.org/content/repositories/snapshots/",
                "releases": {
                  "enabled": "true",
                  "updatePolicy": "always",
                  "checksumPolicy": "fail"
                },
                "snapshots": {
                  "enabled": "tre",
                  "updatePolicy": "always",
                  "checksumPolicy": "fail"
                }
              }
            ]
          output_file: .mvn/settings.xml
      - name: Show config
        run: cat .mvn/settings.xml
      - name: Initial Build
        run: ./mvnw install -DskipTests
#      - name: Hide core's main
#        run: rm -rf core/src/main/java
      - name: Apply rewrites
        run: |
          ./mvnw -e -U org.openrewrite.maven:rewrite-maven-plugin:run \
            -Drewrite.recipeArtifactCoordinates=dev.morphia.morphia:rewrite:3.0.0-SNAPSHOT \
            -Drewrite.activeRecipes=dev.morphia.UpgradeToMorphia30
      - name: Test Compile
        run: ./mvnw test-compile